name: Python Continuous Integration pipeline

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [3.8]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.version }}
        conda-channels: anaconda
    - run: conda --version
    - run: which python

    - name: install dependencies
      env:
        CMAKE_INSTALL_PREFIX: .local
      run: |
        # install reduce from git
        git clone https://github.com/rlabduke/reduce
        mkdir -p build/reduce
        cd build/reduce
        cmake ../../reduce
        make
        sudo make install
        cd ../..
        # Only way to install msms is through conda
        conda install -c bioconda msms 
        # We install pytorch with conda because otherwise it breaks
        conda install pytorch -c pytorch
        # This is the recommended way of installing pytorch-geometric
        conda install pyg -c pyg

    - name: Install the package
      run: pip install .[test]
      env:
        CONDA_PREFIX: /usr/share/miniconda

    - name: Test with pytest
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: |
        pytest --cov-config setup.cfg

    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: python-${{ matrix.version }}
      run: |
        coveralls --service=github
